# Generated by Django 4.1.5 on 2023-01-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_loanorderdelivery_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorderdelivery',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.userpickupstation'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.userpickupstation'),
        ),
    ]
