# Generated by Django 4.1.5 on 2023-03-22 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0004_userpickupstation_selected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpickupstation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userpickupstation',
            unique_together={('station', 'user')},
        ),
    ]
