# Generated by Django 4.1.5 on 2023-03-23 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_alter_userpickupstation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpickupstation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
