# Generated by Django 4.1.5 on 2023-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanorder",
            name="transaction_id",
            field=models.CharField(default="5d5cSA3FL", max_length=250),
        ),
        migrations.AlterField(
            model_name="loanorderinstallments",
            name="transaction_id",
            field=models.CharField(default="SITKWbl2q", max_length=250),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(default="7UvXxd5Jz", max_length=250),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="transaction_id",
            field=models.CharField(default="SITKWbl2q", max_length=250),
        ),
    ]
