# Generated by Django 4.1.5 on 2023-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='s2yAeVQcW', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='hWuNq5H6W', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='pfozn6jnj', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='hWuNq5H6W', max_length=250),
        ),
    ]
