# Generated by Django 4.1.5 on 2023-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_loanorder_complete_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='tywi2SIhg', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='oNDAovUU8', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='9QHCqYOuf', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='oNDAovUU8', max_length=250),
        ),
    ]
