# Generated by Django 4.1.5 on 2023-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='NOXjiITcc', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='cAWvH38ZK', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='UT1e71elH', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='cAWvH38ZK', max_length=250),
        ),
    ]
