# Generated by Django 4.1.5 on 2023-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_order_assigned_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanorder',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='APmgkqsm1', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='TNR6sBFW9', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='ubpArgTvi', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='TNR6sBFW9', max_length=250),
        ),
    ]
