# Generated by Django 4.1.5 on 2023-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_loanorder_arrived_order_arrived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='Q9ZCD9goY', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='phcX1953c', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='xCAosZ422', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='phcX1953c', max_length=250),
        ),
    ]
