# Generated by Django 4.1.5 on 2023-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='1YCz8D2t2', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='J4bJwfJke', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='JNX6dtO92', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='J4bJwfJke', max_length=250),
        ),
    ]
