# Generated by Django 4.2.3 on 2023-07-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_loanorder_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanorder',
            name='transaction_id',
            field=models.CharField(default='OUZMEY6A8', max_length=250),
        ),
        migrations.AlterField(
            model_name='loanorderinstallments',
            name='transaction_id',
            field=models.CharField(default='AOwHLlhWM', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='EQBUjRrgt', max_length=250),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(default='AOwHLlhWM', max_length=250),
        ),
    ]
