# Generated by Django 4.1.7 on 2023-04-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
