# Generated by Django 4.2.3 on 2023-07-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_alter_account_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
