# Generated by Django 4.1.5 on 2023-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faq_rename_user_type_user_type_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DR', 'Driver'), ('FM', 'Finance'), ('SM', 'Sales'), ('RD', 'Rider'), ('CM', 'Customer')], default='CM', max_length=2),
        ),
    ]
